server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/thymeleaf_test?serverTimezone=Asia/Shanghai
    username: root
    password: hannah
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false