management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /monit
  endpoint:
    info:
      enabled: true
    shutdown:
      enabled: true
    health:
      show-details: always
  server:
    port: 8899
spring:
  security:
    user:
      name: admin
      password: admin
