server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/thymeleaf_test?serverTimezone=Asia/Shanghai
    password: hannah
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#  #mybatisPlus配置
#  mybatis-plus:
#    configuration:
#      #开启驼峰映射
#      map-underscore-to-camel-case: true
#    #xml映射地址
#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: true
#    mapper-locations: classpath*:mapper/*.xml