server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/thymeleaf_test?serverTimezone=Asia/Shanghai
    password: hannah
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/
mybatis:
  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.mybatis.entity

